---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

FORMATTERS_DISABLE_ERRORS: false

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE
  - EDITORCONFIG
  - SPELL

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_GIT_DIFF

  # Disabled due to false positives
  - MARKDOWN_MARKDOWN_LINK_CHECK

  # Disabled due to unneeded linting. Checkov, Kics and Trivy are sufficient.
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN

  # Disable due to poor configuration options
  - ACTION_ACTIONLINT

  # Disable since Ruff is used more widely in our code
  - FLAKE8

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# Ignore all file within Git Ignore for linting and security as these will not be pushed to GitHub
IGNORE_GITIGNORED_FILES: true

# Use yml file to allow the use of comments. Megalinter's default is .markdown-lint.json
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown-lint.yml

YAML_V8R_FILTER_REGEX_EXCLUDE: 'dependabot.yml' # Dependabot yaml in SchemaStore is currently not up to date. Dependabot is validated on push by GitHub by default.

PRE_COMMANDS: 
  - command: pip install -r req.txt
    cwd: testing/backend/
    run_before_linters: true