# Local Docker Compose config
---

services:
  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
        VITE_BACKEND_URL: http://localhost:5001
        VITE_SUPPORT_MAIL: digital-landscape@ons.gov.uk
    ports:
      - '127.0.0.1:3000:3000'
    networks:
      - app-network
    depends_on:
      - backend
    user: appuser
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all

  backend:
    build: ./backend
    ports:
      - '127.0.0.1:5001:5001'
    environment:
      - NODE_ENV=development
      - PORT=5001
    env_file:
      - ./backend/.env
    networks:
      - app-network
    user: appuser
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - all

networks:
  app-network:
    driver: bridge
