---
name: Documentation CI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [docs/**]
  pull_request:
    branches: [main]
    paths: [docs/**]
permissions:
  contents: read
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e1148
      - name: Set up Node.js
        uses: actions/setup-python@a0853c2
        with:
          node-version: '24'
      - name: Run Markdown linting
        run: |
          make lint-docs
  verify-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e1148
      - uses: actions/setup-python@a26af69
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@0057852
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: mkdocs build
