# MkDocs CI workflow
---

name: MkDocs CI

on:
  push:
    branches: [main]
    paths:
      - 'mkdocs/**'
  pull_request:
    branches: [main]
    paths:
      - 'mkdocs/**'

permissions:
  contents: read

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js Dependencies
        run: cd mkdocs && make setup-dev

      - name: Run Linting
        run: cd mkdocs && make lint

  verify-docs-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set up cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
      - run: |
          cd mkdocs
          pip install -r mkdocs_requirements.txt
      - name: Verify MkDocs Build
        id: build
        run: |
          PYTHONPATH=. mkdocs build -f mkdocs/mkdocs.yml
